### PR TITLE
Fix: the last rows of the input stream are not always written to the excel file

### PR DESCRIPTION
**Pull request by n-e**
When end() is called on XLSXWriteStream, _finalize does not wait for toXlsxRow to be flushed/ended before writting the footer and finalizing the zip file.

### CODE REVIEW

**Comment by chamilu** [comment]
Facing the same issue. Hope this gets merge asap. @n-e Great fix. Thanks

**Comment by Jule-** [comment]
Hi!
Thanks for the feedback and the pull request! (and sorry for the late response)

Is there any chance that you can add a test case in order to check this use case in order to benefits from a tested lib for further updates? 🙂 
After that I will be more than happy to merge your PR and release the patch!

**Comment by Jule-** [comment]
@n-e I have published your fix under `2.0.1`, still interested in minimal code reproduction if you have this.
Thank you for your contribution! 🙂

**Comment by n-e** [comment]
Hi @Jule- thanks for the merge.

Unfortunately I didn't manage to make a minimal repro and could only check it fixed the problem on the "full" code. Though that bugs me, I'll try again if I have some time.

**Comment by Jule-** [comment]
You are welcome! Thanks again! 🙂

**Pull request merged**
